const CATEGORY_MAP = {
  // ─────────────────────────────
  // ABSENT
  // ─────────────────────────────
  abacuse: { label: "ABACUS" },
  apple: { label: "APPLES" },
  bagel: { label: "BAGELS" },
  ball: { label: "BALLS" },
  balloon: { label: "BALLOONS" },
  barbiedoll: { label: "BARBIE DOLLS" },
  baseballcard: { label: "BASEBALL CARDS" },
  bear: { label: "TEDDY BEARS" },
  benche: { label: "BENCHES" },
  bike: { label: "BICYCLES" },
  boot: { label: "BOOTS" },
  bucket: { label: "BUCKETS" },
  butterflie: { label: "BUTTERFLIES" },
  button: { label: "BUTTONS" },
  calculator: { label: "CALCULATORS" },
  cig: { label: "CIGARETTES" },
  clock: { label: "CLOCKS" },
  coin: { label: "COINS" },
  cookingpan: { label: "COOKING PANS" },
  crib: { label: "CRIBS" },
  dog: { label: "DOGS" },
  dresser: { label: "DRESSERS" },
  earring: { label: "EARRINGS" },
  easteregg: { label: "EASTER EGGS" },
  exercisegear: { label: "EXERCISE GEAR" },
  fan: { label: "FANS" },
  grill: { label: "GRILLS" },
  handheldgame: { label: "HANDHELD GAMES" },
  headband: { label: "HEADBANDS" },
  helmet: { label: "HELMETS" },
  hourglasse: { label: "HOURGLASSES" },
  jacket: { label: "JACKETS" },
  jackolantern: { label: "JACK-O'-LANTERNS" },
  kayak: { label: "KAYAKS" },
  keyboard: { label: "KEYBOARDS" },
  keychain: { label: "KEYCHAINS" },
  knive: { label: "KNIVES" },
  lei: { label: "LEIS" },
  microwave: { label: "MICROWAVES" },
  motorcycle: { label: "MOTORCYCLES" },
  mp3: { label: "MP3 PLAYERS" },
  muffin: { label: "MUFFINS" },
  mug: { label: "MUGS" },
  patioloungechair: { label: "PATIO LOUNGE CHAIRS" },
  pen: { label: "PENS" },
  pillow: { label: "PILLOWS" },
  pitcher: { label: "PITCHERS" },
  radio: { label: "RADIOS" },
  ringbinder: { label: "RING BINDERS" },
  rollerskate: { label: "ROLLER SKATES" },
  rosarie: { label: "ROSARIES" },
  rug: { label: "RUGS" },
  scrunchie: { label: "SCRUNCHIES" },
  sippycup: { label: "SIPPY CUPS" },
  spoon: { label: "SPOONS" },
  stocking: { label: "STOCKINGS" },
  tong: { label: "TONGS" },
  trophie: { label: "TROPHIES" },
  trunk: { label: "TRUNKS" },
  turtle: { label: "TURTLES" },
  tv: { label: "TVS" },
  vase: { label: "VASES" },
  videogamecontroller: { label: "VIDEO GAME CONTROLLERS" },
  watche: { label: "WATCHES" },
  wineglasse: { label: "WINE GLASSES" },
  wreath: { label: "WREATHS" },

  // ─────────────────────────────
  // PRESENT 
  // ─────────────────────────────
  abacuses_domino: { label: "ABACUSES" },
  apples_ball: { label: "APPLES" },
  bagels_donut: { label: "BAGELS" },
  balloons_ball: { label: "BALLOONS" },
  balls_yarn: { label: "BALLS" },
  barbiedolls_doll: { label: "BARBIE DOLLS" },
  baseballcards_pokercard: { label: "BASEBALL CARDS" },
  bears_rabbit: { label: "TEDDY BEARS" },
  benches_chair: { label: "BENCHES" },
  bikes_tricycle: { label: "BICYCLES" },
  boots_shoe: { label: "BOOTS" },
  buckets_cup: { label: "BUCKETS" },
  butterflies_bowtie: { label: "BUTTERFLIES" },
  buttons_coin: { label: "BUTTONS" },
  calculators_phone: { label: "CALCULATORS" },
  cigs_stamp: { label: "CIGARETTES" },
  clocks_plate: { label: "CLOCKS" },
  coins_cookie: { label: "COINS" },
  cookingpans_cookingpot: { label: "COOKING PANS" },
  cribs_bench: { label: "CRIBS" },
  dogs_cat: { label: "DOGS" },
  dressers_trunk: { label: "DRESSERS" },
  earrings_fishhook: { label: "EARRINGS" },
  easteregg_babushkadoll: { label: "EASTER EGGS" },
  exercisegear_lawnmowers: { label: "EXERCISE GEAR" },
  fans_peacock: { label: "FANS" },
  grills_garbagecan: { label: "GRILLS" },
  handheldgame_calculator: { label: "HANDHELD GAMES" },
  headbands_collar: { label: "HEADBANDS" },
  helmets_hat: { label: "HELMETS" },
  hourglasses_lantern: { label: "HOURGLASSES" },
  jackets_longsleeveshirt: { label: "JACKETS" },
  jackolanterns_mask: { label: "JACK-O'-LANTERNS" },
  kayaks_fishhook: { label: "KAYAKS" },
  keyboard_handheldgame: { label: "KEYBOARDS" },
  keychains_key: { label: "KEYCHAINS" },
  knives_pen: { label: "KNIVES" },
  leis_scrunchie: { label: "LEIS" },
  microwaves_tv: { label: "MICROWAVES" },
  motorcycles_bike: { label: "MOTORCYCLES" },
  mp3s_handheldgame: { label: "MP3 PLAYERS" },
  muffins_cupcake: { label: "MUFFINS" },
  mugs_cup: { label: "MUGS" },
  patioloungechair_bench: { label: "PATIO LOUNGE CHAIRS" },
  pens_razor: { label: "PENS" },
  pillows_rug: { label: "PILLOWS" },
  pitchers_vase: { label: "PITCHERS" },
  radios_tv: { label: "RADIOS" },
  ringbinder_book: { label: "RING BINDERS" },
  rollerskates_boot: { label: "ROLLER SKATES" },
  rosaries_necklace: { label: "ROSARIES" },
  rugs_stamp: { label: "RUGS" },
  scrunchie_donut: { label: "SCRUNCHIES" },
  sippycups_mug: { label: "SIPPY CUPS" },
  spoons_fork: { label: "SPOONS" },
  stockings_sock: { label: "STOCKINGS" },
  tongs_nunchuck: { label: "TONGS" },
  trophies_vase: { label: "TROPHIES" },
  trunks_suitcase: { label: "TRUNKS" },
  turtles_tape: { label: "TURTLES" },
  tvs_trunk: { label: "TVS" },
  vases_saltshaker: { label: "VASES" },
  videogamecontrollers_calculator: { label: "VIDEO GAME CONTROLLERS" },
  watches_ring: { label: "WATCHES" },
  wineglasses_vase: { label: "WINE GLASSES" },
  wreaths_scrunchie: { label: "WREATHS" },
};